# Uses the REST Client extension for VS Code to send requests to the server

POST https://bc3bfdbf48e0335c8a052a5706c444e2.qality.tech/tvt/trades/ HTTP/1.1
content-type: application/json

{
    "strategy": "BotifyX",
    "order": "sell",
    "contracts": 0.18,
    "ticker": "SOLUSDT.P",
    "position_size": -0.18
}

### Test with MT String
POST https://bc3bfdbf48e0335c8a052a5706c444e2.qality.tech/tvt/trades/ HTTP/1.1
content-type: application/json

"strategy":"BotifyX", "order":"sell", "contracts":"0.18", "ticker":"SOLUSDT.P", "position_size":"-0.18"