"""Add new columns to PropFirm

Revision ID: 111af910ca38
Revises: Added new columns to the PropFirm model to easily configure them.
Create Date: 2025-01-22 19:14:59.695984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111af910ca38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False, server_default='default_user'))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False, server_default='default_pass'))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=100), nullable=False, server_default='127.0.0.1'))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False, server_default='8080'))
        batch_op.add_column(sa.Column('platform_type', sa.String(length=100), nullable=False, server_default='MT4'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.drop_column('platform_type')
        batch_op.drop_column('port')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
