"""v2

Revision ID: 2f7d781a062c
Revises:
Create Date: 2025-06-09 14:42:20.316529

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f7d781a062c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prop_firms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("full_balance", sa.Float(), nullable=False),
        sa.Column("available_balance", sa.Float(), nullable=False),
        sa.Column("drawdown_percentage", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("platform_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=False),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("contracts", sa.Float(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("position_size", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trade_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trading_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("logged_at", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "prop_firm_trade_pair_association",
        sa.Column("prop_firm_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("trade_pair_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prop_firm_id"],
            ["prop_firms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_pair_id"],
            ["trade_pairs.id"],
        ),
        sa.PrimaryKeyConstraint("prop_firm_id", "trade_pair_id"),
    )
    op.create_table(
        "trades",
        sa.Column("prop_firm_id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=True),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prop_firm_id"],
            ["prop_firms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("prop_firm_id", "signal_id"),
    )
    op.create_table(
        "user_prop_firm",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prop_firm_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prop_firm_id"],
            ["prop_firms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "prop_firm_id"),
    )
    op.create_table(
        "user_trading_strategy",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trading_strategy_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_strategy_id"],
            ["trading_strategies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "trading_strategy_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_trading_strategy")
    op.drop_table("user_prop_firm")
    op.drop_table("trades")
    op.drop_table("prop_firm_trade_pair_association")
    op.drop_table("users")
    op.drop_table("trading_strategies")
    op.drop_table("trade_pairs")
    op.drop_table("signals")
    op.drop_table("prop_firms")
    # ### end Alembic commands ###
