""" dowdown_percentage renamed to drawdown_percentage

Revision ID: 449097f185f5
Revises: 88a6cd75441b
Create Date: 2025-04-22 20:11:31.741476

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "449097f185f5"
down_revision = "88a6cd75441b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prop_firms", schema=None) as batch_op:
        batch_op.alter_column(
            "dowdown_percentage",
            new_column_name="drawdown_percentage",
            existing_type=sa.Float(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prop_firms", schema=None) as batch_op:
        batch_op.alter_column(
            "drawdown_percentage",
            new_column_name="dowdown_percentage",
            existing_type=sa.Float(),
            nullable=False,
        )
