"""added prop trade pair association

Revision ID: 6fdd2076b3ba
Revises: a4e3375671be
Create Date: 2025-02-18 21:12:34.847007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '6fdd2076b3ba'
down_revision = 'a4e3375671be'
branch_labels = None
depends_on = None


def has_table(table_name):
    """Check if a table exists in the database"""
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop_firm_trade_pair_association',
                    sa.Column('prop_firm_id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(length=100), nullable=False),
                    sa.Column('trade_pair_id', sa.Integer(), nullable=False),
                    sa.Column('platform_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['prop_firm_id'], ['prop_firms.id'], ),
                    sa.ForeignKeyConstraint(
                        ['trade_pair_id'], ['trade_pairs.id'], ),
                    sa.PrimaryKeyConstraint('prop_firm_id', 'trade_pair_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prop_firm_trade_pair_association')
    # ### end Alembic commands ###
