"""Add trading strategies and user_trading_strategy tables

Revision ID: 88a6cd75441b
Revises: c2ebf40b5f4c
Create Date: 2025-03-29 14:07:53.695332

"""

from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88a6cd75441b"
down_revision = "c2ebf40b5f4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if context.has_table("trading_strategies"):
        op.drop_table("trading_strategies")
    if context.has_table("user_trading_strategy"):
        op.drop_table("user_trading_strategy")

    op.create_table(
        "trading_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "user_trading_strategy",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trading_strategy_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_strategy_id"],
            ["trading_strategies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "trading_strategy_id"),
    )
    with op.batch_alter_table("prop_firm_trades", schema=None) as batch_op:
        batch_op.alter_column(
            "prop_firm_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("trade_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(
            "fk_prop_firm_trades_trades_trade_id",
            "trades",
            ["trade_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_prop_firm_trades_prop_firms_prop_firm_id",
            "prop_firms",
            ["prop_firm_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prop_firm_trades", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_prop_firm_trades_prop_firms_prop_firm_id", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_prop_firm_trades_trades_trade_id", type_="foreignkey"
        )
        batch_op.alter_column("trade_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("prop_firm_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_table("user_trading_strategy")
    op.drop_table("trading_strategies")
    # ### end Alembic commands ###
