"""added ticker to trade

Revision ID: 8dbd8f04647e
Revises: 3866e2fff6b0
Create Date: 2025-06-15 13:23:42.457937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbd8f04647e'
down_revision = '3866e2fff6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###
