"""empty message

Revision ID: a400590b0786
Revises: 74e57edae4bd
Create Date: 2025-02-24 20:38:12.617848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a400590b0786'
down_revision = '74e57edae4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firm_trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firm_trades', schema=None) as batch_op:
        batch_op.drop_column('platform_id')

    # ### end Alembic commands ###
