"""added trade pairs

Revision ID: a4e3375671be
Revises: e933400c8ad9
Create Date: 2025-02-18 20:23:45.971087

"""
from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e3375671be'
down_revision = 'e933400c8ad9'
branch_labels = None
depends_on = None


def upgrade():
    if not context.has_table('prop_firm_trades'):
        op.create_table('prop_firm_trades',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('prop_firm_id', sa.Integer(),
                                  nullable=False),
                        sa.Column('trade_pair_id',
                                  sa.Integer(), nullable=False),
                        sa.Column('trade_id', sa.Integer(), nullable=False),
                        sa.Column('platform_id', sa.Integer(), nullable=True),
                        )

    # ### commands auto generated by Alembic - please adjust! ###
    if not context.has_table('trade_pairs'):
        op.create_table('trade_pairs',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(
                            length=100), nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_pairs')
    op.drop_table('prop_firm_trades')
    # ### end Alembic commands ###
