"""Add the trades table

Revision ID: b400590b0786
Revises: a400590b0786
Create Date: 2025-02-24 20:38:12.617848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'b400590b0786'
down_revision = 'a400590b0786'
branch_labels = None
depends_on = None


def has_table(table_name):
    """Check if a table exists in the database"""
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()


def has_column(table_name, column_name):
    """Check if a column exists in a table"""
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = [c['name'] for c in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if has_table('trades'):
        with op.batch_alter_table('trades', schema=None) as batch_op:
            # Check if the column 'platform_id' exists
            if not has_column('trades', 'id'):
                batch_op.add_column(
                    sa.Column('id', sa.Integer(), nullable=False))
            if not has_column('trades', 'strategy'):
                batch_op.add_column(
                    sa.Column('strategy', sa.String(length=100), nullable=False))
            if not has_column('trades', 'order_type'):
                batch_op.add_column(
                    sa.Column('order_type', sa.String(length=10), nullable=False))
            if not has_column('trades', 'contracts'):
                batch_op.add_column(
                    sa.Column('contracts', sa.Float(), nullable=False))
            if not has_column('trades', 'ticker'):
                batch_op.add_column(
                    sa.Column('ticker', sa.String(length=20), nullable=False))
            if not has_column('trades', 'position_size'):
                batch_op.add_column(
                    sa.Column('position_size', sa.Float(), nullable=False))
            if not has_column('trades', 'created_at'):
                batch_op.add_column(
                    sa.Column('created_at', sa.DateTime(),
                              default=sa.func.now(), nullable=False))
    else:
        op.create_table(
            'trades',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('strategy', sa.String(length=100), nullable=False),
            sa.Column('order_type', sa.String(length=10), nullable=False),
            sa.Column('contracts', sa.Float(), nullable=False),
            sa.Column('ticker', sa.String(length=20), nullable=False),
            sa.Column('position_size', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(),
                      default=sa.func.now(), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if has_table('trades'):
        op.drop_table('trades')

    # ### end Alembic commands ###
