"""empty message

Revision ID: c2ebf40b5f4c
Revises: a30fb23bede0
Create Date: 2025-03-20 20:24:19.295142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ebf40b5f4c'
down_revision = 'a30fb23bede0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('logged_at')

    # ### end Alembic commands ###
