"""empty message

Revision ID: cbdbc9d0493b
Revises: b400590b0786
Create Date: 2025-03-04 21:11:58.786064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdbc9d0493b'
down_revision = 'b400590b0786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firm_trade_pair_association', schema=None) as batch_op:
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('prop_firm_trades', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_prop_firm_id', 'prop_firms', ['prop_firm_id'], ['id'])
        batch_op.create_foreign_key('fk_trade_id', 'trades', ['trade_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('trade_pair_id')

    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('prop_firm_trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_pair_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_prop_firm_id', type_='foreignkey')
        batch_op.drop_constraint('fk_trade_id', type_='foreignkey')

    with op.batch_alter_table('prop_firm_trade_pair_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
