"""prop firm description

Revision ID: e12250a660ae
Revises: 8dbd8f04647e
Create Date: 2025-06-18 20:28:57.164210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12250a660ae'
down_revision = '8dbd8f04647e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_firms', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
